### ISSUE TITLE
March 27, 2020

### ISSUE THREAD

**Issue by nickgartmann** [abstractcoder/digital-public-works#45]
Agenda:
- Discuss call with Code for Milwaukee
- Heroku credits application through Code for America
- Organizations
- Next features: Needs? Feedback?

**Comment by abstractcoder** [comment]
Meeting Notes

**Heroku credits application**

In Andrew's hands to submit.

**Organization Changes**
- Give Project Owner Ability to Publish/Unpublish
- Search Projects show all published projects
- Show Only Endorsed Project Filter on Search Project Screen
- Add Organization Name to project
- Changing Add/Remove Project to Endorse/Unendorsed

**Next Features**
- Project Needs
- Vanity Project URL
- Social cards
